version: '3.7'

services:
  order:
    build: ../../
    dockerfile: docker/dev/Dockerfile.order
    env_file: .env
    depends_on:
      - order-db
    volumes:
      - order-vol:/application/node_modules

  payment:
    build: ../../
    dockerfile: docker/dev/Dockerfile.payment
    env_file: .env
    volumes:
      - payment-vol:/application/node_modules

  order-db:
    image: postgres:11.1-alpine
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_ORDER_DB}

volumes:
  order-vol:
  payment-vol: