FROM node:11.6.0
LABEL maintainer="alexkomp.ua@gmail.com"

COPY docker/dev/scripts/entrypoint.order.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
CMD ["npm", "run", "test"]

COPY order-service /application
WORKDIR /application