version: '3.7'

services:
  order:
    build: 
      context: ../../
      dockerfile: docker/prod/Dockerfile.order
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - order-db
      - payment

  payment:
    build: 
      context: ../../
      dockerfile: docker/prod/Dockerfile.payment
    env_file: .env

  order-db:
    image: postgres:11.1-alpine
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_ORDER_DB}
